function add_pmsm_foc_stateflow_v21
%ADD_PMSM_FOC_STATEFLOW_V21 Add a dual-rate motor supervisor and safety gate.
% The 1 ms Stateflow chart owns operating modes and the supervisory PWM
% request. A separate 100 us fast-safety gate owns the final PWM permit so
% overcurrent protection never waits for the slow task. It
% implements INIT -> READY -> CALIB -> ALIGN -> RUN and an acknowledged,
% latched FAULT path. Simulink remains responsible for numeric FOC,
% parameterized current-offset calibration, alignment-voltage selection and
% dual-rate protection input conditioning. The standalone scalar boundary is
% wrapped by typed buses after this integration step.

versionDirectory = fileparts(mfilename('fullpath'));
previousDirectory = pwd;
directoryCleanup = onCleanup(@() cd(previousDirectory));
cd(versionDirectory);

controllerName = 'PMSM_FOC_DualPlant_Controller_v21';
harnessName = 'PMSM_FOC_DualPlant_ClosedLoop_v21';
controllerFile = fullfile(versionDirectory, [controllerName '.slx']);
harnessFile = fullfile(versionDirectory, [harnessName '.slx']);

load_system('simulink');
load_system('sflib');
load_system(controllerFile);
load_system(harnessFile);

integrateStateManager(controllerName, false);
integrateStateManager(harnessName, true);

save_system(controllerName, [], 'OverwriteIfChangedOnDisk', true);
save_system(harnessName, [], 'OverwriteIfChangedOnDisk', true);

fprintf('CODEX_STATEFLOW_CONTROLLER_PRESENT=1\n');
fprintf('CODEX_STATEFLOW_HARNESS_PRESENT=1\n');
fprintf('CODEX_STATEFLOW_STATE_COUNT=6\n');
fprintf('CODEX_STATEFLOW_SAMPLE_TIME_S=0.001\n');
fprintf('CODEX_FAST_SAFETY_SAMPLE_TIME_S=0.0001\n');
fprintf('CODEX_SLOW_SAFETY_SAMPLE_TIME_S=0.001\n');
fprintf('CODEX_STATEFLOW_CALIBRATION_COMPONENT=1\n');
fprintf('CODEX_STATEFLOW_ALIGNMENT_COMPONENT=1\n');
fprintf('CODEX_STATEFLOW_ACKNOWLEDGED_FAULT_RESET=1\n');
fprintf('CODEX_STATEFLOW_INTEGRATION_PASS=1\n');
end

function integrateStateManager(modelName, isHarness)
removePreviousIntegration(modelName);
cleanupDanglingLines(modelName);

chartPath = [modelName '/Motor_Supervisor_1ms'];
add_block('sflib/Chart', chartPath, 'Position', [150 650 390 845], ...
    'BackgroundColor', 'lightBlue');
buildStateflowChart(modelName, chartPath);

componentDefinitions = { ...
    'Command_Arbiter_1ms', [400 650 620 835], 'yellow'; ...
    'Fast_Protection_100us', [700 650 900 790], 'orange'; ...
    'Slow_Safety_Monitor_1ms', [700 820 900 970], 'yellow'; ...
    'Fault_Latch_Manager_100us', [990 650 1240 930], 'orange'; ...
    'Final_PWM_Arbiter_100us', [1320 650 1530 790], 'orange'; ...
    'Current_Offset_Calibration_100us', [400 900 650 1125], 'lightBlue'; ...
    'Alignment_DQ_Override_100us', [1130 330 1350 485], 'lightBlue'};
for componentIndex = 1:size(componentDefinitions, 1)
    add_block('simulink/Ports & Subsystems/Subsystem', ...
        [modelName '/' componentDefinitions{componentIndex, 1}], ...
        'Position', componentDefinitions{componentIndex, 2}, ...
        'BackgroundColor', componentDefinitions{componentIndex, 3});
end
buildCommandArbiter([modelName '/Command_Arbiter_1ms']);
buildFastProtection([modelName '/Fast_Protection_100us']);
buildSlowSafetyMonitor([modelName '/Slow_Safety_Monitor_1ms']);
buildFaultLatchManager([modelName '/Fault_Latch_Manager_100us']);
buildFinalPwmArbiter([modelName '/Final_PWM_Arbiter_100us']);
buildCurrentOffsetCalibration([modelName '/Current_Offset_Calibration_100us']);
buildAlignmentOverride([modelName '/Alignment_DQ_Override_100us']);

add_block('simulink/Math Operations/Product', ...
    [modelName '/Stateflow_Speed_Command_Gate'], 'Inputs', '**', ...
    'Position', [65 45 95 85], 'BackgroundColor', 'lightBlue');

rateTransitions = { ...
    'AnyFault_To_1ms', '0.001', [1250 720 1360 755]; ...
    'CalibrationDone_To_1ms', '0.001', [680 1020 800 1055]; ...
    'EmergencyStop_To_1ms', '0.001', [250 885 365 920]; ...
    'DriverFault_To_1ms', '0.001', [250 925 365 960]; ...
    'HardwareGate_To_1ms', '0.001', [250 965 365 1000]; ...
    'SupervisorPwmRequest_To_100us', '0.0001', [1320 590 1460 625]; ...
    'CalibrationEnable_To_100us', '0.0001', [405 850 535 885]; ...
    'CalibrationReset_To_100us', '0.0001', [545 850 675 885]; ...
    'AlignmentEnable_To_100us', '0.0001', [1090 520 1220 555]; ...
    'ControllerReset_To_100us', '0.0001', [550 585 680 620]; ...
    'ResetAllowed_To_100us', '0.0001', [850 590 970 625]; ...
    'Overspeed_To_100us', '0.0001', [910 820 1015 855]; ...
    'Undervoltage_To_100us', '0.0001', [910 860 1015 895]; ...
    'Overvoltage_To_100us', '0.0001', [910 900 1015 935]};
for gatewayIndex = 1:size(rateTransitions, 1)
    gatewayPath = [modelName '/' rateTransitions{gatewayIndex, 1}];
    add_block('simulink/Signal Attributes/Rate Transition', gatewayPath, ...
        'OutPortSampleTime', rateTransitions{gatewayIndex, 2}, ...
        'Position', rateTransitions{gatewayIndex, 3}, ...
        'BackgroundColor', 'orange');
    set_param(gatewayPath, 'Description', ...
        'Explicit dual-rate snapshot/hold boundary required by ARC-005.');
    if endsWith(rateTransitions{gatewayIndex, 1}, '_To_100us')
        % Protected, minimum-latency slow-to-fast transfer. Keeping data
        % integrity while clearing maximum-delay determinism prevents an
        % extra 1 ms delay in Stop -> SupervisorPwmRequest -> final PWM.
        set_param(gatewayPath, 'Integrity', 'on', 'Deterministic', 'off');
    end
end

if isHarness
    addHarnessTestStimuli(modelName);
    addStateLogging(modelName);
else
    scalarPorts = { ...
        'StartRequest', '7'; 'StopRequest', '8'; ...
        'EmergencyStop', '9'; 'DriverFault', '10'; ...
        'FaultResetRequest', '11'; 'HardwareGate', '12'; ...
        'MeasurementValid', '13'};
    for portIndex = 1:size(scalarPorts, 1)
        add_block('simulink/Sources/In1', ...
            [modelName '/' scalarPorts{portIndex, 1}], ...
            'Port', scalarPorts{portIndex, 2}, 'OutDataTypeStr', 'boolean', ...
            'Position', [20 610 + 35 * portIndex 50 624 + 35 * portIndex]);
    end
    add_block('simulink/Sinks/Terminator', ...
        [modelName '/Motor_State_Code_Terminator'], ...
        'Position', [430 790 450 810]);
end

disconnectInport([modelName '/Speed_PI_Controller_1ms'], 1);
disconnectInport([modelName '/Speed_PI_Controller_1ms'], 3);
disconnectInport([modelName '/D_Axis_Current_PI'], 3);
disconnectInport([modelName '/Q_Axis_Current_PI'], 3);
disconnectInport([modelName '/Clarke_Transform'], 1);
disconnectInport([modelName '/Clarke_Transform'], 2);
for inversePort = 1:4
    disconnectInport([modelName '/Inverse_Park_Transform'], inversePort);
end
disconnectInport([modelName '/VdCommand'], 1);
disconnectInport([modelName '/VqCommand'], 1);
if isHarness
    for phaseIndex = 1:3
        disconnectInport([modelName '/Native_Average_Inverter'], phaseIndex);
    end
    disconnectInport([modelName '/Duty_A_Log'], 1);
end

if isHarness
    sources = struct( ...
        'SpeedReference', 'Speed_Reference_Rpm/1', ...
        'SpeedFeedback', 'Selectable_PMSM_Plant/1', ...
        'PhaseCurrentA', 'Measured_Current_A_With_Test_Offset/1', ...
        'PhaseCurrentB', 'Measured_Current_B_With_Test_Offset/1', ...
        'DcBus', 'DC_Bus_48V/1', ...
        'Start', 'Start_Request_Command/1', ...
        'Stop', 'Stop_Request_Command/1', ...
        'Emergency', 'Emergency_Stop_Command/1', ...
        'DriverFault', 'Driver_Fault_Command/1', ...
        'Reset', 'Fault_Reset_Request/1', ...
        'HardwareGate', 'Hardware_Gate_Command/1', ...
        'MeasurementValid', 'Measurement_Valid_Command/1');
else
    sources = struct( ...
        'SpeedReference', 'SpeedReferenceRpm/1', ...
        'SpeedFeedback', 'SpeedRpm/1', ...
        'PhaseCurrentA', 'PhaseCurrentA/1', ...
        'PhaseCurrentB', 'PhaseCurrentB/1', ...
        'DcBus', 'DcBusVoltage/1', ...
        'Start', 'StartRequest/1', 'Stop', 'StopRequest/1', ...
        'Emergency', 'EmergencyStop/1', 'DriverFault', 'DriverFault/1', ...
        'Reset', 'FaultResetRequest/1', 'HardwareGate', 'HardwareGate/1', ...
        'MeasurementValid', 'MeasurementValid/1');
end

% Explicit command priority: emergency/fault > stop > start.
add_line(modelName, sources.Start, 'Command_Arbiter_1ms/1', 'autorouting', 'on');
add_line(modelName, sources.Stop, 'Command_Arbiter_1ms/2', 'autorouting', 'on');
add_line(modelName, sources.Emergency, 'EmergencyStop_To_1ms/1', 'autorouting', 'on');
add_line(modelName, 'EmergencyStop_To_1ms/1', 'Command_Arbiter_1ms/3', 'autorouting', 'on');
add_line(modelName, sources.DriverFault, 'DriverFault_To_1ms/1', 'autorouting', 'on');
add_line(modelName, 'DriverFault_To_1ms/1', 'Command_Arbiter_1ms/4', 'autorouting', 'on');
add_line(modelName, sources.Reset, 'Command_Arbiter_1ms/5', 'autorouting', 'on');
add_line(modelName, sources.HardwareGate, 'HardwareGate_To_1ms/1', 'autorouting', 'on');
add_line(modelName, 'HardwareGate_To_1ms/1', 'Command_Arbiter_1ms/6', 'autorouting', 'on');
add_line(modelName, 'Command_Arbiter_1ms/1', 'Motor_Supervisor_1ms/1', 'autorouting', 'on');
add_line(modelName, 'Command_Arbiter_1ms/2', 'Motor_Supervisor_1ms/2', 'autorouting', 'on');
add_line(modelName, 'Command_Arbiter_1ms/3', 'Motor_Supervisor_1ms/4', 'autorouting', 'on');
add_line(modelName, 'Command_Arbiter_1ms/3', 'ResetAllowed_To_100us/1', 'autorouting', 'on');

% Fast and slow protection feed one latch manager; only it owns fault latches.
add_line(modelName, sources.PhaseCurrentA, 'Fast_Protection_100us/1', 'autorouting', 'on');
add_line(modelName, sources.PhaseCurrentB, 'Fast_Protection_100us/2', 'autorouting', 'on');
add_line(modelName, sources.MeasurementValid, 'Fast_Protection_100us/3', 'autorouting', 'on');
add_line(modelName, sources.SpeedFeedback, 'Slow_Safety_Monitor_1ms/1', 'autorouting', 'on');
add_line(modelName, sources.DcBus, 'Slow_Safety_Monitor_1ms/2', 'autorouting', 'on');
add_line(modelName, 'Slow_Safety_Monitor_1ms/2', 'Overspeed_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'Slow_Safety_Monitor_1ms/3', 'Undervoltage_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'Slow_Safety_Monitor_1ms/4', 'Overvoltage_To_100us/1', 'autorouting', 'on');
faultInputs = {sources.Emergency, sources.DriverFault, ...
    'Fast_Protection_100us/1', 'Fast_Protection_100us/2', ...
    'Overspeed_To_100us/1', 'Undervoltage_To_100us/1', ...
    'Overvoltage_To_100us/1', 'ResetAllowed_To_100us/1'};
for faultIndex = 1:numel(faultInputs)
    add_line(modelName, faultInputs{faultIndex}, ...
        sprintf('Fault_Latch_Manager_100us/%d', faultIndex), ...
        'autorouting', 'on');
end
add_line(modelName, 'Fault_Latch_Manager_100us/4', 'AnyFault_To_1ms/1', 'autorouting', 'on');
add_line(modelName, 'AnyFault_To_1ms/1', 'Motor_Supervisor_1ms/3', 'autorouting', 'on');

% Stateflow owns only the supervisory request. The final permission exists once.
add_line(modelName, 'Motor_Supervisor_1ms/2', 'SupervisorPwmRequest_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'SupervisorPwmRequest_To_100us/1', 'Final_PWM_Arbiter_100us/1', 'autorouting', 'on');
add_line(modelName, 'Fault_Latch_Manager_100us/1', 'Final_PWM_Arbiter_100us/2', 'autorouting', 'on');
add_line(modelName, sources.HardwareGate, 'Final_PWM_Arbiter_100us/3', 'autorouting', 'on');

% Calibration, numeric FOC and alignment remain separated from mode logic.
add_line(modelName, sources.PhaseCurrentA, 'Current_Offset_Calibration_100us/1', 'autorouting', 'on');
add_line(modelName, sources.PhaseCurrentB, 'Current_Offset_Calibration_100us/2', 'autorouting', 'on');
add_line(modelName, 'Motor_Supervisor_1ms/4', 'CalibrationEnable_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'CalibrationEnable_To_100us/1', 'Current_Offset_Calibration_100us/3', 'autorouting', 'on');
add_line(modelName, 'Motor_Supervisor_1ms/5', 'CalibrationReset_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'CalibrationReset_To_100us/1', 'Current_Offset_Calibration_100us/4', 'autorouting', 'on');
add_line(modelName, 'Current_Offset_Calibration_100us/5', 'CalibrationDone_To_1ms/1', 'autorouting', 'on');
add_line(modelName, 'CalibrationDone_To_1ms/1', 'Motor_Supervisor_1ms/5', 'autorouting', 'on');
add_line(modelName, 'Current_Offset_Calibration_100us/1', 'Clarke_Transform/1', 'autorouting', 'on');
add_line(modelName, 'Current_Offset_Calibration_100us/2', 'Clarke_Transform/2', 'autorouting', 'on');

add_line(modelName, sources.SpeedReference, 'Stateflow_Speed_Command_Gate/1', 'autorouting', 'on');
add_line(modelName, 'Motor_Supervisor_1ms/1', 'Stateflow_Speed_Command_Gate/2', 'autorouting', 'on');
add_line(modelName, 'Stateflow_Speed_Command_Gate/1', 'Speed_PI_Controller_1ms/1', 'autorouting', 'on');
add_line(modelName, 'Motor_Supervisor_1ms/7', 'Speed_PI_Controller_1ms/3', 'autorouting', 'on');
add_line(modelName, 'Motor_Supervisor_1ms/7', 'ControllerReset_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'ControllerReset_To_100us/1', 'D_Axis_Current_PI/3', 'autorouting', 'on');
add_line(modelName, 'ControllerReset_To_100us/1', 'Q_Axis_Current_PI/3', 'autorouting', 'on');

alignmentSources = {'DQ_Voltage_Command/1', 'DQ_Voltage_Command/2', ...
    'Electrical_Angle_Trig_100us/1', 'Electrical_Angle_Trig_100us/2'};
for alignmentIndex = 1:4
    add_line(modelName, alignmentSources{alignmentIndex}, ...
        sprintf('Alignment_DQ_Override_100us/%d', alignmentIndex), ...
        'autorouting', 'on');
    add_line(modelName, sprintf('Alignment_DQ_Override_100us/%d', alignmentIndex), ...
        sprintf('Inverse_Park_Transform/%d', alignmentIndex), ...
        'autorouting', 'on');
end
add_line(modelName, 'Motor_Supervisor_1ms/6', 'AlignmentEnable_To_100us/1', 'autorouting', 'on');
add_line(modelName, 'AlignmentEnable_To_100us/1', 'Alignment_DQ_Override_100us/5', 'autorouting', 'on');
if ~isHarness
    add_line(modelName, 'Alignment_DQ_Override_100us/1', 'VdCommand/1', 'autorouting', 'on');
    add_line(modelName, 'Alignment_DQ_Override_100us/2', 'VqCommand/1', 'autorouting', 'on');
    add_line(modelName, 'Motor_Supervisor_1ms/3', 'Motor_State_Code_Terminator/1', 'autorouting', 'on');
end

if isHarness
    adapterPath = [modelName '/Average_Plant_Enable_Map'];
    add_block('simulink/Ports & Subsystems/Subsystem', adapterPath, ...
        'Position', [1640 150 1830 300], 'BackgroundColor', 'gray');
    buildAveragePlantEnableMap(adapterPath);
    for phaseIndex = 1:3
        add_line(modelName, sprintf('SVPWM_Duty_Calculation/%d', phaseIndex), ...
            sprintf('Average_Plant_Enable_Map/%d', phaseIndex), 'autorouting', 'on');
        add_line(modelName, sprintf('Average_Plant_Enable_Map/%d', phaseIndex), ...
            sprintf('Native_Average_Inverter/%d', phaseIndex), 'autorouting', 'on');
    end
    add_line(modelName, 'Final_PWM_Arbiter_100us/1', 'Average_Plant_Enable_Map/4', 'autorouting', 'on');
    add_line(modelName, 'Average_Plant_Enable_Map/1', 'Duty_A_Log/1', 'autorouting', 'on');
    loggingSources = { ...
        'Motor_Supervisor_1ms/1', 'Final_PWM_Arbiter_100us/1', ...
        'Motor_Supervisor_1ms/3', 'Motor_Supervisor_1ms/4', ...
        'Current_Offset_Calibration_100us/5', 'Motor_Supervisor_1ms/6', ...
        'Current_Offset_Calibration_100us/3', 'Current_Offset_Calibration_100us/4', ...
        'Current_Offset_Calibration_100us/1', 'Current_Offset_Calibration_100us/2', ...
        'Alignment_DQ_Override_100us/1', 'Alignment_DQ_Override_100us/2', ...
        sources.Reset, 'Fault_Latch_Manager_100us/4', ...
        'Fault_Latch_Manager_100us/5', 'AlignmentEnable_To_100us/1', ...
        'Motor_Supervisor_1ms/2', 'SupervisorPwmRequest_To_100us/1', ...
        'Fault_Latch_Manager_100us/2', 'Fault_Latch_Manager_100us/3', ...
        sources.Start, sources.Stop, sources.Emergency, sources.DriverFault, ...
        sources.HardwareGate, 'Fast_Protection_100us/2', ...
        'Command_Arbiter_1ms/3'};
    for loggingIndex = 1:numel(loggingSources)
        add_line(modelName, loggingSources{loggingIndex}, ...
            sprintf('Motor_Stateflow_Test_Logging/%d', loggingIndex), ...
            'autorouting', 'on');
    end
end

addStateflowAnnotation(modelName);
addTaskContractAnnotation(modelName);
cleanupDanglingLines(modelName);
end

function buildStateflowChart(modelName, chartPath)
rootObject = sfroot;
machine = rootObject.find('-isa', 'Stateflow.Machine', 'Name', modelName);
assert(~isempty(machine), 'Stateflow machine was not created for %s.', modelName);
chart = machine.find('-isa', 'Stateflow.Chart', 'Name', ...
    'Motor_Supervisor_1ms');
assert(~isempty(chart), 'Stateflow chart was not created for %s.', modelName);
chart = chart(1);
chart.ActionLanguage = 'C';
chart.ChartUpdate = 'DISCRETE';
chart.SampleTime = '0.001';

addChartData(chart, 'StartAccepted', 'Input', 1, 'boolean');
addChartData(chart, 'StopActive', 'Input', 2, 'boolean');
addChartData(chart, 'FaultDetected', 'Input', 3, 'boolean');
addChartData(chart, 'ResetAllowed', 'Input', 4, 'boolean');
addChartData(chart, 'CalibrationDone', 'Input', 5, 'boolean');
addChartData(chart, 'ControlEnable', 'Output', 1, 'boolean');
addChartData(chart, 'SupervisorPwmRequest', 'Output', 2, 'boolean');
addChartData(chart, 'StateCode', 'Output', 3, 'uint8');
addChartData(chart, 'CalibrationEnable', 'Output', 4, 'boolean');
addChartData(chart, 'CalibrationReset', 'Output', 5, 'boolean');
addChartData(chart, 'AlignmentEnable', 'Output', 6, 'boolean');
addChartData(chart, 'ControllerReset', 'Output', 7, 'boolean');
addChartParameter(chart, 'PMSM_Calibration_TimeoutTicks', 'uint16');
addChartParameter(chart, 'PMSM_Alignment_DurationTicks', 'uint16');

supervisedState = Stateflow.State(chart);
supervisedState.Name = 'SUPERVISED';
% Keep enough internal margin for the stop-to-INIT return transitions so
% Stateflow routes the whole line inside this decomposition boundary.
supervisedState.Position = [20 40 710 300];
supervisedState.LabelString = 'SUPERVISED';

initState = addState(supervisedState, 'INIT', [25 85 105 82], ...
    1, 0, 0, 0, 1, 0, 1);
readyState = addState(supervisedState, 'READY', [155 85 105 82], ...
    2, 0, 0, 0, 0, 0, 1);
calibState = addState(supervisedState, 'CALIB', [285 85 105 82], ...
    3, 0, 0, 1, 0, 0, 1);
alignState = addState(supervisedState, 'ALIGN', [415 85 105 82], ...
    4, 0, 1, 0, 0, 1, 1);
runState = addState(supervisedState, 'RUN', [545 85 105 82], ...
    5, 1, 1, 0, 0, 0, 0);
faultState = addState(chart, 'FAULT', [785 105 120 92], ...
    6, 0, 0, 0, 1, 0, 1);

defaultTransition = Stateflow.Transition(chart);
defaultTransition.Destination = initState;
defaultTransition.DestinationOClock = 0;
defaultTransition.SourceEndPoint = [77 25];
defaultTransition.MidPoint = [77 45];

addTransition(supervisedState, initState, readyState, ...
    'after(1,tick)', 3, 9);
addTransition(supervisedState, readyState, calibState, ...
    '[StartAccepted && !StopActive]', 3, 9);
addTransition(supervisedState, calibState, alignState, ...
    '[CalibrationDone]', 3, 9);
addTransition(chart, calibState, faultState, ...
    'after(PMSM_Calibration_TimeoutTicks,tick)', 3, 9);
addTransition(supervisedState, alignState, runState, ...
    'after(PMSM_Alignment_DurationTicks,tick)', 3, 9);
addTransition(supervisedState, calibState, initState, '[StopActive]', 6, 6);
addTransition(supervisedState, alignState, initState, '[StopActive]', 6, 6);
addTransition(supervisedState, runState, initState, '[StopActive]', 6, 6);
addTransition(chart, supervisedState, faultState, '[FaultDetected]', 3, 9);
addTransition(chart, faultState, initState, ...
    '[ResetAllowed && !FaultDetected && StopActive]', 9, 6);

chartPathHandle = getSimulinkBlockHandle(chartPath);
assert(chartPathHandle ~= -1, 'Stateflow chart block is missing.');
end

function data = addChartData(chart, name, scope, port, primitiveType)
data = Stateflow.Data(chart);
data.Name = name;
data.Scope = scope;
data.Port = port;
data.Props.Type.Method = 'Built-in';
data.Props.Type.Primitive = primitiveType;
end

function data = addChartParameter(chart, name, primitiveType)
data = Stateflow.Data(chart);
data.Name = name;
data.Scope = 'Parameter';
data.Props.Type.Method = 'Built-in';
data.Props.Type.Primitive = primitiveType;
end

function state = addState(chart, name, position, code, controlEnable, ...
        supervisorPwmRequest, calibrationEnable, calibrationReset, alignmentEnable, ...
        controllerReset)
state = Stateflow.State(chart);
state.Name = name;
state.Position = position;
state.LabelString = sprintf(['%s\nentry:\n' ...
    ' ControlEnable = %d;\n SupervisorPwmRequest = %d;\n StateCode = %d;\n' ...
    ' CalibrationEnable = %d;\n CalibrationReset = %d;\n' ...
    ' AlignmentEnable = %d;\n ControllerReset = %d;'], ...
    name, controlEnable, supervisorPwmRequest, code, calibrationEnable, ...
    calibrationReset, alignmentEnable, controllerReset);
end

function transition = addTransition(chart, sourceState, destinationState, ...
        label, sourceClock, destinationClock)
transition = Stateflow.Transition(chart);
transition.Source = sourceState;
transition.Destination = destinationState;
transition.LabelString = label;
transition.SourceOClock = sourceClock;
transition.DestinationOClock = destinationClock;
end

function buildCommandArbiter(parent)
Simulink.SubSystem.deleteContents(parent);
inputNames = {'StartRequest', 'StopRequest', 'EmergencyStopHeld', ...
    'DriverFaultHeld', 'FaultResetRequest', 'HardwareGateHeld'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 60 + 55 * inputIndex 50 74 + 55 * inputIndex]);
end
outputNames = {'StartAccepted', 'StopActive', 'ResetAllowed'};
for outputIndex = 1:numel(outputNames)
    add_block('simulink/Sinks/Out1', [parent '/' outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [555 110 + 90 * outputIndex 585 124 + 90 * outputIndex]);
end
notDefinitions = {'NoStop','StopRequest'; 'NoEmergency','EmergencyStopHeld'; ...
    'NoDriverFault','DriverFaultHeld'; 'NoStart','StartRequest'};
for notIndex = 1:size(notDefinitions, 1)
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [parent '/' notDefinitions{notIndex, 1}], 'Operator', 'NOT', ...
        'Position', [150 70 + 65 * notIndex 195 100 + 65 * notIndex]);
    add_line(parent, [notDefinitions{notIndex, 2} '/1'], ...
        [notDefinitions{notIndex, 1} '/1'], 'autorouting', 'on');
end
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Accept_Start'], 'Operator', 'AND', 'Inputs', '5', ...
    'Position', [340 95 390 205]);
startInputs = {'StartRequest/1','NoStop/1','NoEmergency/1', ...
    'NoDriverFault/1','HardwareGateHeld/1'};
for inputIndex = 1:numel(startInputs)
    add_line(parent, startInputs{inputIndex}, ...
        sprintf('Accept_Start/%d', inputIndex), 'autorouting', 'on');
end
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Accept_Reset'], 'Operator', 'AND', 'Inputs', '6', ...
    'Position', [340 255 390 385]);
resetInputs = {'FaultResetRequest/1','StopRequest/1','NoStart/1', ...
    'NoEmergency/1','NoDriverFault/1','HardwareGateHeld/1'};
for inputIndex = 1:numel(resetInputs)
    add_line(parent, resetInputs{inputIndex}, ...
        sprintf('Accept_Reset/%d', inputIndex), 'autorouting', 'on');
end
add_line(parent, 'Accept_Start/1', 'StartAccepted/1', 'autorouting', 'on');
add_line(parent, 'StopRequest/1', 'StopActive/1', 'autorouting', 'on');
add_line(parent, 'Accept_Reset/1', 'ResetAllowed/1', 'autorouting', 'on');
annotation = Simulink.Annotation(parent, sprintf([ ...
    'RESPONSIBILITY: explicit command priority and reset preconditions\n' ...
    'Task: 1 ms | Priority: emergency/fault > stop > start\n' ...
    'Start/Stop/Reset are level sampled; producer shall hold >= 1 ms.\n' ...
    'No internal debounce. Reset requires stop, start clear, faults clear and hardware gate.']));
annotation.Position = [70 10 560 90];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'yellow';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildFastProtection(parent)
Simulink.SubSystem.deleteContents(parent);
inputNames = {'PhaseCurrentA', 'PhaseCurrentB', 'MeasurementValid'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 80 + 75 * inputIndex 50 94 + 75 * inputIndex]);
end
outputNames = {'SoftwareOvercurrent', 'MeasurementInvalid'};
for outputIndex = 1:numel(outputNames)
    add_block('simulink/Sinks/Out1', [parent '/' outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [500 135 + 100 * outputIndex 530 149 + 100 * outputIndex]);
end
add_block('simulink/Math Operations/Abs', [parent '/Abs_Ia'], ...
    'Position', [100 130 135 160]);
add_block('simulink/Math Operations/Abs', [parent '/Abs_Ib'], ...
    'Position', [100 205 135 235]);
add_block('simulink/Sources/Constant', [parent '/Max_Current_A'], ...
    'Value', 'PMSM_Protection_MaxCurrent_A', 'OutDataTypeStr', 'single', ...
    'Position', [105 275 175 305]);
for phaseName = {'A', 'B'}
    phaseIndex = double(phaseName{1}) - double('A') + 1;
    add_block('simulink/Logic and Bit Operations/Relational Operator', ...
        [parent '/OverCurrent' phaseName{1}], 'Operator', '>', ...
        'Position', [225 105 + 90 * phaseIndex 270 140 + 90 * phaseIndex]);
end
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Any_Overcurrent'], 'Operator', 'OR', 'Inputs', '2', ...
    'Position', [330 170 375 235]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Invalid_Measurement'], 'Operator', 'NOT', ...
    'Position', [330 280 375 310]);
add_line(parent, 'PhaseCurrentA/1', 'Abs_Ia/1', 'autorouting', 'on');
add_line(parent, 'PhaseCurrentB/1', 'Abs_Ib/1', 'autorouting', 'on');
add_line(parent, 'Abs_Ia/1', 'OverCurrentA/1', 'autorouting', 'on');
add_line(parent, 'Abs_Ib/1', 'OverCurrentB/1', 'autorouting', 'on');
add_line(parent, 'Max_Current_A/1', 'OverCurrentA/2', 'autorouting', 'on');
add_line(parent, 'Max_Current_A/1', 'OverCurrentB/2', 'autorouting', 'on');
add_line(parent, 'OverCurrentA/1', 'Any_Overcurrent/1', 'autorouting', 'on');
add_line(parent, 'OverCurrentB/1', 'Any_Overcurrent/2', 'autorouting', 'on');
add_line(parent, 'Any_Overcurrent/1', 'SoftwareOvercurrent/1', 'autorouting', 'on');
add_line(parent, 'MeasurementValid/1', 'Invalid_Measurement/1', 'autorouting', 'on');
add_line(parent, 'Invalid_Measurement/1', 'MeasurementInvalid/1', 'autorouting', 'on');
annotation = Simulink.Annotation(parent, sprintf([ ...
    'RESPONSIBILITY: raw 100 us protection decisions only\n' ...
    'Software overcurrent latency <= 1 fast tick; invalid measurement is same-cycle.\n' ...
    'No latch and no PWM ownership in this component.']));
annotation.Position = [80 10 500 85];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'orange';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildFaultLatchManager(parent)
Simulink.SubSystem.deleteContents(parent);
faultNames = {'EmergencyStop','DriverFault','SoftwareOvercurrent', ...
    'MeasurementInvalid','Overspeed','Undervoltage','Overvoltage'};
for inputIndex = 1:numel(faultNames)
    add_block('simulink/Sources/In1', [parent '/' faultNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 45 + 55 * inputIndex 50 59 + 55 * inputIndex]);
end
add_block('simulink/Sources/In1', [parent '/ResetAllowed'], 'Port', '8', ...
    'Position', [20 485 50 499]);
outputNames = {'FastInterlock','FaultBits','FaultCode', ...
    'AnyFaultLatched','CurrentLimitActive'};
for outputIndex = 1:numel(outputNames)
    add_block('simulink/Sinks/Out1', [parent '/' outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [1080 90 + 85 * outputIndex 1110 104 + 85 * outputIndex]);
end
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Any_Raw_Fault'], 'Operator', 'OR', 'Inputs', '7', ...
    'Position', [110 420 160 555]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/No_Raw_Fault'], 'Operator', 'NOT', ...
    'Position', [200 470 245 500]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Reset_Permitted'], 'Operator', 'AND', 'Inputs', '2', ...
    'Position', [285 450 330 505]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Keep_Latches'], 'Operator', 'NOT', ...
    'Position', [370 465 415 495]);
for faultIndex = 1:numel(faultNames)
    y = 45 + 55 * faultIndex;
    stateName = [faultNames{faultIndex} '_Latch_State'];
    holdName = [faultNames{faultIndex} '_Set_Or_Hold'];
    nextName = [faultNames{faultIndex} '_Latched'];
    add_block('simulink/Discrete/Unit Delay', [parent '/' stateName], ...
        'InitialCondition', 'false', 'SampleTime', '0.0001', ...
        'Position', [240 y 295 y + 30]);
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [parent '/' holdName], 'Operator', 'OR', 'Inputs', '2', ...
        'Position', [345 y - 10 390 y + 45]);
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [parent '/' nextName], 'Operator', 'AND', 'Inputs', '2', ...
        'Position', [455 y - 10 500 y + 45]);
    add_line(parent, [faultNames{faultIndex} '/1'], ...
        sprintf('Any_Raw_Fault/%d', faultIndex), 'autorouting', 'on');
    add_line(parent, [faultNames{faultIndex} '/1'], [holdName '/1'], ...
        'autorouting', 'on');
    add_line(parent, [stateName '/1'], [holdName '/2'], 'autorouting', 'on');
    add_line(parent, [holdName '/1'], [nextName '/1'], 'autorouting', 'on');
    add_line(parent, 'Keep_Latches/1', [nextName '/2'], 'autorouting', 'on');
    add_line(parent, [nextName '/1'], [stateName '/1'], 'autorouting', 'on');
end
add_line(parent, 'Any_Raw_Fault/1', 'No_Raw_Fault/1', 'autorouting', 'on');
add_line(parent, 'ResetAllowed/1', 'Reset_Permitted/1', 'autorouting', 'on');
add_line(parent, 'No_Raw_Fault/1', 'Reset_Permitted/2', 'autorouting', 'on');
add_line(parent, 'Reset_Permitted/1', 'Keep_Latches/1', 'autorouting', 'on');

add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Any_Latched_Fault'], 'Operator', 'OR', 'Inputs', '7', ...
    'Position', [575 175 625 310]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Interlock_OK'], 'Operator', 'NOT', ...
    'Position', [680 215 725 245]);
for faultIndex = 1:numel(faultNames)
    nextName = [faultNames{faultIndex} '_Latched'];
    add_line(parent, [nextName '/1'], ...
        sprintf('Any_Latched_Fault/%d', faultIndex), 'autorouting', 'on');
end
add_line(parent, 'Any_Latched_Fault/1', 'Interlock_OK/1', 'autorouting', 'on');
add_line(parent, 'Interlock_OK/1', 'FastInterlock/1', 'autorouting', 'on');
add_line(parent, 'Any_Latched_Fault/1', 'AnyFaultLatched/1', 'autorouting', 'on');
add_line(parent, 'SoftwareOvercurrent_Latched/1', ...
    'CurrentLimitActive/1', 'autorouting', 'on');

bitSources = cell(1, numel(faultNames));
for faultIndex = 1:numel(faultNames)
    convertName = sprintf('FaultBit%d_U32', faultIndex - 1);
    weightName = sprintf('FaultBit%d_Weight', faultIndex - 1);
    add_block('simulink/Signal Attributes/Data Type Conversion', ...
        [parent '/' convertName], 'OutDataTypeStr', 'uint32', ...
        'Position', [575 330 + 38 * faultIndex 635 360 + 38 * faultIndex]);
    add_block('simulink/Math Operations/Gain', [parent '/' weightName], ...
        'Gain', sprintf('uint32(%d)', 2^(faultIndex - 1)), ...
        'OutDataTypeStr', 'uint32', ...
        'Position', [675 330 + 38 * faultIndex 740 360 + 38 * faultIndex]);
    add_line(parent, [faultNames{faultIndex} '_Latched/1'], ...
        [convertName '/1'], 'autorouting', 'on');
    add_line(parent, [convertName '/1'], [weightName '/1'], 'autorouting', 'on');
    bitSources{faultIndex} = [weightName '/1'];
end
add_block('simulink/Math Operations/Sum', [parent '/Pack_Fault_Bits'], ...
    'Inputs', repmat('+', 1, numel(faultNames)), ...
    'OutDataTypeStr', 'uint32', 'Position', [800 365 845 555]);
for faultIndex = 1:numel(bitSources)
    add_line(parent, bitSources{faultIndex}, ...
        sprintf('Pack_Fault_Bits/%d', faultIndex), 'autorouting', 'on');
end
add_line(parent, 'Pack_Fault_Bits/1', 'FaultBits/1', 'autorouting', 'on');

add_block('simulink/Sources/Constant', [parent '/FaultCode_0'], ...
    'Value', 'uint16(0)', 'OutDataTypeStr', 'uint16', ...
    'Position', [580 650 640 680]);
previousCodeSource = 'FaultCode_0/1';
for faultIndex = numel(faultNames):-1:1
    switchName = sprintf('FaultCode_Priority_%d', faultIndex);
    constantName = sprintf('FaultCode_%d', faultIndex);
    y = 620 + 42 * (numel(faultNames) - faultIndex + 1);
    add_block('simulink/Sources/Constant', [parent '/' constantName], ...
        'Value', sprintf('uint16(%d)', faultIndex), ...
        'OutDataTypeStr', 'uint16', 'Position', [660 y 720 y + 30]);
    add_block('simulink/Signal Routing/Switch', [parent '/' switchName], ...
        'Criteria', 'u2 ~= 0', 'Position', [790 y - 5 835 y + 45]);
    add_line(parent, [constantName '/1'], [switchName '/1'], 'autorouting', 'on');
    add_line(parent, [faultNames{faultIndex} '_Latched/1'], ...
        [switchName '/2'], 'autorouting', 'on');
    add_line(parent, previousCodeSource, [switchName '/3'], 'autorouting', 'on');
    previousCodeSource = [switchName '/1'];
end
add_line(parent, previousCodeSource, 'FaultCode/1', 'autorouting', 'on');
annotation = Simulink.Annotation(parent, sprintf([ ...
    'RESPONSIBILITY: unique fault latch, bit allocation and reset owner\n' ...
    'Task: 100 us | bits/codes 1..7: EStop, driver, OC, invalid measurement, overspeed, UV, OV\n' ...
    'FastInterlock = NOT AnyFaultLatched. Reset only when ResetAllowed AND no raw fault.']));
annotation.Position = [95 10 870 90];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'orange';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildFinalPwmArbiter(parent)
Simulink.SubSystem.deleteContents(parent);
inputNames = {'SupervisorPwmRequest','FastInterlock','HardwareGate'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 70 + 70 * inputIndex 50 84 + 70 * inputIndex]);
end
add_block('simulink/Sinks/Out1', [parent '/FinalPwmEnable'], ...
    'Port', '1', 'Position', [430 205 460 219]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Three_Level_AND'], 'Operator', 'AND', 'Inputs', '3', ...
    'Position', [240 135 295 260]);
for inputIndex = 1:numel(inputNames)
    add_line(parent, [inputNames{inputIndex} '/1'], ...
        sprintf('Three_Level_AND/%d', inputIndex), 'autorouting', 'on');
end
add_line(parent, 'Three_Level_AND/1', 'FinalPwmEnable/1', 'autorouting', 'on');
annotation = Simulink.Annotation(parent, sprintf([ ...
    'SINGLE PWM OWNERSHIP POINT (ARC-004)\n' ...
    'FinalPwmEnable = SupervisorPwmRequest AND FastInterlock AND HardwareGate\n' ...
    'Each input independently disables output in the 100 us task; no duty-value substitute.']));
annotation.Position = [70 15 465 90];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'orange';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildAveragePlantEnableMap(parent)
Simulink.SubSystem.deleteContents(parent);
inputNames = {'DutyARequest','DutyBRequest','DutyCRequest','FinalPwmEnable'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 55 + 60 * inputIndex 50 69 + 60 * inputIndex]);
end
for phaseIndex = 1:3
    phaseName = char('A' + phaseIndex - 1);
    add_block('simulink/Sinks/Out1', [parent '/AppliedDuty' phaseName], ...
        'Port', num2str(phaseIndex), ...
        'Position', [430 70 + 80 * phaseIndex 460 84 + 80 * phaseIndex]);
    add_block('simulink/Signal Routing/Switch', ...
        [parent '/PlantDutySelect' phaseName], 'Criteria', 'u2 ~= 0', ...
        'Position', [275 55 + 80 * phaseIndex 320 105 + 80 * phaseIndex]);
end
add_block('simulink/Sources/Constant', [parent '/Zero_Line_Voltage_Duty'], ...
    'Value', 'PMSM_SafeDuty', 'OutDataTypeStr', 'single', ...
    'Position', [110 315 195 345]);
for phaseIndex = 1:3
    phaseName = char('A' + phaseIndex - 1);
    add_line(parent, ['Duty' phaseName 'Request/1'], ...
        ['PlantDutySelect' phaseName '/1'], 'autorouting', 'on');
    add_line(parent, 'FinalPwmEnable/1', ...
        ['PlantDutySelect' phaseName '/2'], 'autorouting', 'on');
    add_line(parent, 'Zero_Line_Voltage_Duty/1', ...
        ['PlantDutySelect' phaseName '/3'], 'autorouting', 'on');
    add_line(parent, ['PlantDutySelect' phaseName '/1'], ...
        ['AppliedDuty' phaseName '/1'], 'autorouting', 'on');
end
annotation = Simulink.Annotation(parent, sprintf([ ...
    'HARNESS-ONLY AVERAGE-PLANT ADAPTER\n' ...
    'Disabled PWM is mapped internally to equal 0.5 duties to produce zero line voltage.\n' ...
    'This is not controller PWM gating and is absent from generated controller code.']));
annotation.Position = [65 10 475 90];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'gray';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildSlowSafetyMonitor(parent)
Simulink.SubSystem.deleteContents(parent);
inputNames = {'SpeedRpm', 'DcBusVoltage'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 70 + 90 * inputIndex 50 84 + 90 * inputIndex]);
end
outputNames = {'SlowFaultDetected','OverspeedDetected', ...
    'UndervoltageDetected','OvervoltageDetected'};
for outputIndex = 1:numel(outputNames)
    add_block('simulink/Sinks/Out1', [parent '/' outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [590 110 + 75 * outputIndex 620 124 + 75 * outputIndex]);
end
add_block('simulink/Discrete/Zero-Order Hold', [parent '/Speed_Sample_1ms'], ...
    'SampleTime', '0.001', 'Position', [80 145 145 175]);
add_block('simulink/Discrete/Zero-Order Hold', [parent '/Vdc_Sample_1ms'], ...
    'SampleTime', '0.001', 'Position', [80 235 145 265]);
add_block('simulink/Math Operations/Abs', [parent '/Abs_Speed'], ...
    'Position', [175 145 210 175]);
add_block('simulink/Sources/Constant', [parent '/Max_Speed_Rpm'], ...
    'Value', 'PMSM_Protection_MaxSpeed_Rpm', 'OutDataTypeStr', 'single', ...
    'Position', [175 80 235 110]);
add_block('simulink/Sources/Constant', [parent '/Min_Vdc'], ...
    'Value', 'PMSM_Protection_MinDcBus_V', 'OutDataTypeStr', 'single', ...
    'Position', [175 290 235 320]);
add_block('simulink/Sources/Constant', [parent '/Max_Vdc'], ...
    'Value', 'PMSM_Protection_MaxDcBus_V', 'OutDataTypeStr', 'single', ...
    'Position', [175 345 235 375]);
comparisonNames = {'OverSpeed', 'UnderVoltage', 'OverVoltage'};
operators = {'>', '<', '>'};
for comparisonIndex = 1:numel(comparisonNames)
    add_block('simulink/Logic and Bit Operations/Relational Operator', ...
        [parent '/' comparisonNames{comparisonIndex}], ...
        'Operator', operators{comparisonIndex}, ...
        'Position', [300 90 + 100 * comparisonIndex ...
        345 125 + 100 * comparisonIndex]);
end
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Any_Slow_Fault'], 'Operator', 'OR', 'Inputs', '3', ...
    'Position', [450 185 500 310]);
add_line(parent, 'SpeedRpm/1', 'Speed_Sample_1ms/1', 'autorouting', 'on');
add_line(parent, 'DcBusVoltage/1', 'Vdc_Sample_1ms/1', 'autorouting', 'on');
add_line(parent, 'Speed_Sample_1ms/1', 'Abs_Speed/1', 'autorouting', 'on');
add_line(parent, 'Abs_Speed/1', 'OverSpeed/1', 'autorouting', 'on');
add_line(parent, 'Max_Speed_Rpm/1', 'OverSpeed/2', 'autorouting', 'on');
add_line(parent, 'Vdc_Sample_1ms/1', 'UnderVoltage/1', 'autorouting', 'on');
add_line(parent, 'Min_Vdc/1', 'UnderVoltage/2', 'autorouting', 'on');
add_line(parent, 'Vdc_Sample_1ms/1', 'OverVoltage/1', 'autorouting', 'on');
add_line(parent, 'Max_Vdc/1', 'OverVoltage/2', 'autorouting', 'on');
for comparisonIndex = 1:numel(comparisonNames)
    add_line(parent, [comparisonNames{comparisonIndex} '/1'], ...
        sprintf('Any_Slow_Fault/%d', comparisonIndex), 'autorouting', 'on');
end
add_line(parent, 'Any_Slow_Fault/1', 'SlowFaultDetected/1', 'autorouting', 'on');
add_line(parent, 'OverSpeed/1', 'OverspeedDetected/1', 'autorouting', 'on');
add_line(parent, 'UnderVoltage/1', 'UndervoltageDetected/1', 'autorouting', 'on');
add_line(parent, 'OverVoltage/1', 'OvervoltageDetected/1', 'autorouting', 'on');
annotation = Simulink.Annotation(parent, sprintf([ ...
    'RESPONSIBILITY: low-bandwidth operating-envelope supervision\n' ...
    'Task: 1 ms | outputs keep independent fault identity\n' ...
    'Limits are sourced from PMSM_FOC_Data.sldd']));
annotation.Position = [95 15 550 75];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'yellow';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildCurrentOffsetCalibration(parent)
% Numeric 100-sample averaging stays in Simulink. Stateflow only starts or
% resets this component and waits for CalibrationDone.
Simulink.SubSystem.deleteContents(parent);
inputNames = {'RawIa', 'RawIb', 'CalibrationEnable', 'CalibrationReset'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 55 + 70 * inputIndex 50 69 + 70 * inputIndex]);
end
outputNames = {'CorrectedIa', 'CorrectedIb', 'OffsetIa', 'OffsetIb', ...
    'CalibrationDone'};
for outputIndex = 1:numel(outputNames)
    add_block('simulink/Sinks/Out1', [parent '/' outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [760 45 + 65 * outputIndex 790 59 + 65 * outputIndex]);
end

add_block('simulink/Sources/Constant', [parent '/Zero'], ...
    'Value', 'single(0.0)', 'OutDataTypeStr', 'single', ...
    'Position', [75 390 125 420]);
add_block('simulink/Sources/Constant', [parent '/One'], ...
    'Value', 'single(1.0)', 'OutDataTypeStr', 'single', ...
    'Position', [75 440 125 470]);
add_block('simulink/Sources/Constant', [parent '/Sample_Target'], ...
    'Value', 'PMSM_Calibration_SampleCount', 'OutDataTypeStr', 'single', ...
    'Position', [75 490 145 520]);

stateNames = {'SumA_State', 'SumB_State', 'Count_State'};
stateY = [155 245 335];
for stateIndex = 1:numel(stateNames)
    add_block('simulink/Discrete/Unit Delay', ...
        [parent '/' stateNames{stateIndex}], ...
        'InitialCondition', 'single(0.0)', 'SampleTime', '0.0001', ...
        'Position', [235 stateY(stateIndex) 290 stateY(stateIndex) + 30]);
end

add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [parent '/Count_Below_Target'], 'Operator', '<', ...
    'Position', [185 455 225 485]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [parent '/Accumulate_Enable'], 'Operator', 'AND', 'Inputs', '2', ...
    'Position', [280 430 325 475]);
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [parent '/Count_Positive'], 'Operator', '>', ...
    'Position', [345 485 385 515]);
add_block('simulink/Logic and Bit Operations/Relational Operator', ...
    [parent '/Count_Complete'], 'Operator', '>=', ...
    'Position', [665 350 710 380]);

add_block('simulink/Math Operations/Sum', [parent '/SumA_Add'], ...
    'Inputs', '++', 'Position', [345 125 375 180]);
add_block('simulink/Math Operations/Sum', [parent '/SumB_Add'], ...
    'Inputs', '++', 'Position', [345 215 375 270]);
add_block('simulink/Math Operations/Sum', [parent '/Count_Add'], ...
    'Inputs', '++', 'Position', [345 305 375 360]);

holdNames = {'SumA_Hold', 'SumB_Hold', 'Count_Hold'};
resetNames = {'SumA_Reset', 'SumB_Reset', 'Count_Reset'};
switchY = [130 220 310];
for switchIndex = 1:numel(holdNames)
    add_block('simulink/Signal Routing/Switch', ...
        [parent '/' holdNames{switchIndex}], 'Criteria', 'u2 ~= 0', ...
        'Position', [420 switchY(switchIndex) 465 switchY(switchIndex) + 50]);
    add_block('simulink/Signal Routing/Switch', ...
        [parent '/' resetNames{switchIndex}], 'Criteria', 'u2 ~= 0', ...
        'Position', [505 switchY(switchIndex) 550 switchY(switchIndex) + 50]);
end

add_block('simulink/Math Operations/Product', [parent '/OffsetA_Calculate'], ...
    'Inputs', '*/', 'Position', [430 535 475 575]);
add_block('simulink/Math Operations/Product', [parent '/OffsetB_Calculate'], ...
    'Inputs', '*/', 'Position', [430 605 475 645]);
add_block('simulink/Signal Routing/Switch', [parent '/OffsetA_Valid'], ...
    'Criteria', 'u2 ~= 0', 'Position', [535 525 580 580]);
add_block('simulink/Signal Routing/Switch', [parent '/OffsetB_Valid'], ...
    'Criteria', 'u2 ~= 0', 'Position', [535 595 580 650]);
add_block('simulink/Math Operations/Sum', [parent '/Correct_Ia'], ...
    'Inputs', '+-', 'Position', [650 115 680 170]);
add_block('simulink/Math Operations/Sum', [parent '/Correct_Ib'], ...
    'Inputs', '+-', 'Position', [650 205 680 260]);

add_line(parent, 'Count_State/1', 'Count_Below_Target/1', 'autorouting', 'on');
add_line(parent, 'Sample_Target/1', 'Count_Below_Target/2', 'autorouting', 'on');
add_line(parent, 'CalibrationEnable/1', 'Accumulate_Enable/1', 'autorouting', 'on');
add_line(parent, 'Count_Below_Target/1', 'Accumulate_Enable/2', 'autorouting', 'on');
add_line(parent, 'Count_State/1', 'Count_Positive/1', 'autorouting', 'on');
add_line(parent, 'Zero/1', 'Count_Positive/2', 'autorouting', 'on');
add_line(parent, 'Count_State/1', 'Count_Complete/1', 'autorouting', 'on');
add_line(parent, 'Sample_Target/1', 'Count_Complete/2', 'autorouting', 'on');
add_line(parent, 'Count_Complete/1', 'CalibrationDone/1', 'autorouting', 'on');

add_line(parent, 'SumA_State/1', 'SumA_Add/1', 'autorouting', 'on');
add_line(parent, 'RawIa/1', 'SumA_Add/2', 'autorouting', 'on');
add_line(parent, 'SumB_State/1', 'SumB_Add/1', 'autorouting', 'on');
add_line(parent, 'RawIb/1', 'SumB_Add/2', 'autorouting', 'on');
add_line(parent, 'Count_State/1', 'Count_Add/1', 'autorouting', 'on');
add_line(parent, 'One/1', 'Count_Add/2', 'autorouting', 'on');

add_line(parent, 'SumA_Add/1', 'SumA_Hold/1', 'autorouting', 'on');
add_line(parent, 'SumB_Add/1', 'SumB_Hold/1', 'autorouting', 'on');
add_line(parent, 'Count_Add/1', 'Count_Hold/1', 'autorouting', 'on');
add_line(parent, 'Accumulate_Enable/1', 'SumA_Hold/2', 'autorouting', 'on');
add_line(parent, 'Accumulate_Enable/1', 'SumB_Hold/2', 'autorouting', 'on');
add_line(parent, 'Accumulate_Enable/1', 'Count_Hold/2', 'autorouting', 'on');
add_line(parent, 'SumA_State/1', 'SumA_Hold/3', 'autorouting', 'on');
add_line(parent, 'SumB_State/1', 'SumB_Hold/3', 'autorouting', 'on');
add_line(parent, 'Count_State/1', 'Count_Hold/3', 'autorouting', 'on');

for resetIndex = 1:numel(resetNames)
    add_line(parent, 'Zero/1', [resetNames{resetIndex} '/1'], 'autorouting', 'on');
    add_line(parent, 'CalibrationReset/1', ...
        [resetNames{resetIndex} '/2'], 'autorouting', 'on');
    add_line(parent, [holdNames{resetIndex} '/1'], ...
        [resetNames{resetIndex} '/3'], 'autorouting', 'on');
    add_line(parent, [resetNames{resetIndex} '/1'], ...
        [stateNames{resetIndex} '/1'], 'autorouting', 'on');
end

add_line(parent, 'SumA_State/1', 'OffsetA_Calculate/1', 'autorouting', 'on');
add_line(parent, 'Count_State/1', 'OffsetA_Calculate/2', 'autorouting', 'on');
add_line(parent, 'SumB_State/1', 'OffsetB_Calculate/1', 'autorouting', 'on');
add_line(parent, 'Count_State/1', 'OffsetB_Calculate/2', 'autorouting', 'on');
add_line(parent, 'OffsetA_Calculate/1', 'OffsetA_Valid/1', 'autorouting', 'on');
add_line(parent, 'OffsetB_Calculate/1', 'OffsetB_Valid/1', 'autorouting', 'on');
add_line(parent, 'Count_Positive/1', 'OffsetA_Valid/2', 'autorouting', 'on');
add_line(parent, 'Count_Positive/1', 'OffsetB_Valid/2', 'autorouting', 'on');
add_line(parent, 'Zero/1', 'OffsetA_Valid/3', 'autorouting', 'on');
add_line(parent, 'Zero/1', 'OffsetB_Valid/3', 'autorouting', 'on');
add_line(parent, 'RawIa/1', 'Correct_Ia/1', 'autorouting', 'on');
add_line(parent, 'OffsetA_Valid/1', 'Correct_Ia/2', 'autorouting', 'on');
add_line(parent, 'RawIb/1', 'Correct_Ib/1', 'autorouting', 'on');
add_line(parent, 'OffsetB_Valid/1', 'Correct_Ib/2', 'autorouting', 'on');
add_line(parent, 'Correct_Ia/1', 'CorrectedIa/1', 'autorouting', 'on');
add_line(parent, 'Correct_Ib/1', 'CorrectedIb/1', 'autorouting', 'on');
add_line(parent, 'OffsetA_Valid/1', 'OffsetIa/1', 'autorouting', 'on');
add_line(parent, 'OffsetB_Valid/1', 'OffsetIb/1', 'autorouting', 'on');

annotation = Simulink.Annotation(parent, sprintf([ ...
    'RESPONSIBILITY: estimate and hold phase-current ADC offsets\n' ...
    'Task: 100 us | Samples: PMSM_Calibration_SampleCount | Reset: INIT/FAULT\n' ...
    'Outputs: corrected Ia/Ib, offsets and CalibrationDone']));
annotation.Position = [110 15 675 85];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'lightBlue';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function buildAlignmentOverride(parent)
% Stateflow grants ALIGN permission; this Simulink component owns the
% data-dictionary alignment voltage and fixed-angle trigonometric selection.
Simulink.SubSystem.deleteContents(parent);
inputNames = {'FocVd', 'FocVq', 'FeedbackSin', 'FeedbackCos', ...
    'AlignmentEnable'};
for inputIndex = 1:numel(inputNames)
    add_block('simulink/Sources/In1', [parent '/' inputNames{inputIndex}], ...
        'Port', num2str(inputIndex), ...
        'Position', [20 60 + 65 * inputIndex 50 74 + 65 * inputIndex]);
end
outputNames = {'AppliedVd', 'AppliedVq', 'AppliedSin', 'AppliedCos'};
for outputIndex = 1:numel(outputNames)
    add_block('simulink/Sinks/Out1', [parent '/' outputNames{outputIndex}], ...
        'Port', num2str(outputIndex), ...
        'Position', [475 85 + 80 * outputIndex 505 99 + 80 * outputIndex]);
end
constantNames = {'Align_Vd', 'Align_Vq', 'Align_Sin', 'Align_Cos'};
constantValues = {'PMSM_Alignment_Vd_V', 'PMSM_Alignment_Vq_V', ...
    'PMSM_Alignment_Sin', 'PMSM_Alignment_Cos'};
switchNames = {'Vd_Select', 'Vq_Select', 'Sin_Select', 'Cos_Select'};
normalSources = {'FocVd/1', 'FocVq/1', 'FeedbackSin/1', 'FeedbackCos/1'};
outputTargets = {'AppliedVd/1', 'AppliedVq/1', 'AppliedSin/1', 'AppliedCos/1'};
for pathIndex = 1:numel(switchNames)
    y = 110 + 80 * pathIndex;
    add_block('simulink/Sources/Constant', ...
        [parent '/' constantNames{pathIndex}], ...
        'Value', constantValues{pathIndex}, 'OutDataTypeStr', 'single', ...
        'Position', [110 y - 40 170 y - 10]);
    add_block('simulink/Signal Routing/Switch', ...
        [parent '/' switchNames{pathIndex}], 'Criteria', 'u2 ~= 0', ...
        'Position', [300 y - 35 345 y + 15]);
    add_line(parent, [constantNames{pathIndex} '/1'], ...
        [switchNames{pathIndex} '/1'], 'autorouting', 'on');
    add_line(parent, 'AlignmentEnable/1', ...
        [switchNames{pathIndex} '/2'], 'autorouting', 'on');
    add_line(parent, normalSources{pathIndex}, ...
        [switchNames{pathIndex} '/3'], 'autorouting', 'on');
    add_line(parent, [switchNames{pathIndex} '/1'], ...
        outputTargets{pathIndex}, 'autorouting', 'on');
end
annotation = Simulink.Annotation(parent, sprintf([ ...
    'RESPONSIBILITY: apply fixed rotor-alignment voltage only in ALIGN\n' ...
    'Parameters: PMSM_Alignment_* from PMSM_FOC_Data.sldd | Task: 100 us']));
annotation.Position = [80 15 445 80];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'lightBlue';
Simulink.BlockDiagram.arrangeSystem(parent);
end

function addHarnessTestStimuli(modelName)
% Harness-only command and fault stimuli. Tests override these model-workspace
% values without changing controller architecture or data-dictionary values.
modelWorkspace = get_param(modelName, 'ModelWorkspace');
assignin(modelWorkspace, 'PMSM_TEST_CURRENT_OFFSET_A', single(0.0));
assignin(modelWorkspace, 'PMSM_TEST_CURRENT_OFFSET_B', single(0.0));
assignin(modelWorkspace, 'PMSM_FAST_OVERCURRENT_SIGNAL', ...
    timeseries(single(0.0), 0.0));
assignin(modelWorkspace, 'PMSM_START_REQUEST_SIGNAL', ...
    timeseries(logical([0 1]), [0 0.05]));
assignin(modelWorkspace, 'PMSM_STOP_REQUEST_SIGNAL', timeseries(false, 0.0));
assignin(modelWorkspace, 'PMSM_EMERGENCY_STOP_SIGNAL', timeseries(false, 0.0));
assignin(modelWorkspace, 'PMSM_DRIVER_FAULT_SIGNAL', timeseries(false, 0.0));
assignin(modelWorkspace, 'PMSM_FAULT_RESET_REQUEST_SIGNAL', timeseries(false, 0.0));
assignin(modelWorkspace, 'PMSM_HARDWARE_GATE_SIGNAL', timeseries(true, 0.0));
assignin(modelWorkspace, 'PMSM_MEASUREMENT_VALID_SIGNAL', timeseries(true, 0.0));

add_block('simulink/Sources/Constant', [modelName '/Test_Current_Offset_A'], ...
    'Value', 'PMSM_TEST_CURRENT_OFFSET_A', 'OutDataTypeStr', 'single', ...
    'Position', [1950 665 2025 695]);
add_block('simulink/Sources/Constant', [modelName '/Test_Current_Offset_B'], ...
    'Value', 'PMSM_TEST_CURRENT_OFFSET_B', 'OutDataTypeStr', 'single', ...
    'Position', [1950 720 2025 750]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Measured_Current_A_With_Test_Offset'], ...
    'Inputs', '+++', 'Position', [2060 640 2090 710]);
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Measured_Current_B_With_Test_Offset'], ...
    'Inputs', '++', 'Position', [2060 715 2090 770]);
add_line(modelName, 'Selectable_PMSM_Plant/3', ...
    'Measured_Current_A_With_Test_Offset/1', 'autorouting', 'on');
add_line(modelName, 'Test_Current_Offset_A/1', ...
    'Measured_Current_A_With_Test_Offset/2', 'autorouting', 'on');
add_block('simulink/Sources/From Workspace', ...
    [modelName '/Fast_Overcurrent_Test_A'], ...
    'VariableName', 'PMSM_FAST_OVERCURRENT_SIGNAL', 'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [1920 610 2040 640]);
add_line(modelName, 'Fast_Overcurrent_Test_A/1', ...
    'Measured_Current_A_With_Test_Offset/3', 'autorouting', 'on');
add_line(modelName, 'Selectable_PMSM_Plant/4', ...
    'Measured_Current_B_With_Test_Offset/1', 'autorouting', 'on');
add_line(modelName, 'Test_Current_Offset_B/1', ...
    'Measured_Current_B_With_Test_Offset/2', 'autorouting', 'on');

commandSources = { ...
    'Start_Request_Command','PMSM_START_REQUEST_SIGNAL'; ...
    'Stop_Request_Command','PMSM_STOP_REQUEST_SIGNAL'; ...
    'Emergency_Stop_Command','PMSM_EMERGENCY_STOP_SIGNAL'; ...
    'Driver_Fault_Command','PMSM_DRIVER_FAULT_SIGNAL'; ...
    'Fault_Reset_Request','PMSM_FAULT_RESET_REQUEST_SIGNAL'; ...
    'Hardware_Gate_Command','PMSM_HARDWARE_GATE_SIGNAL'; ...
    'Measurement_Valid_Command','PMSM_MEASUREMENT_VALID_SIGNAL'};
for sourceIndex = 1:size(commandSources, 1)
    add_block('simulink/Sources/From Workspace', ...
        [modelName '/' commandSources{sourceIndex, 1}], ...
        'VariableName', commandSources{sourceIndex, 2}, 'Interpolate', 'off', ...
        'OutputAfterFinalValue', 'Holding final value', ...
        'Position', [80 860 + 40 * sourceIndex 220 890 + 40 * sourceIndex]);
end
end

function addStateLogging(modelName)
loggingDefinitions = { ...
    'Motor_Control_Enable_Log', 'motor_control_enable'; ...
    'Motor_PWM_Enable_Log', 'motor_pwm_enable'; ...
    'Motor_State_Code_Log', 'motor_state_code'; ...
    'Motor_Calibration_Enable_Log', 'motor_calibration_enable'; ...
    'Motor_Calibration_Done_Log', 'motor_calibration_done'; ...
    'Motor_Alignment_Enable_Log', 'motor_alignment_enable'; ...
    'Motor_Current_Offset_A_Log', 'motor_current_offset_a'; ...
    'Motor_Current_Offset_B_Log', 'motor_current_offset_b'; ...
    'Motor_Corrected_Current_A_Log', 'motor_corrected_current_a'; ...
    'Motor_Corrected_Current_B_Log', 'motor_corrected_current_b'; ...
    'Motor_Applied_Vd_Log', 'motor_applied_vd'; ...
    'Motor_Applied_Vq_Log', 'motor_applied_vq'; ...
    'Motor_Reset_Ack_Log', 'motor_reset_ack'; ...
    'Motor_Fault_Detected_Log', 'motor_fault_detected'; ...
    'Motor_Fast_Fault_Log', 'motor_fast_fault'; ...
    'Motor_Alignment_Command_Held_Log', 'motor_alignment_command_held'; ...
    'Motor_Supervisor_PWM_Request_Log', 'motor_supervisor_pwm_request'; ...
    'Motor_PWM_Request_Held_Log', 'motor_pwm_request_held'; ...
    'Motor_Fault_Bits_Log', 'motor_fault_bits'; ...
    'Motor_Fault_Code_Log', 'motor_fault_code'; ...
    'Motor_Start_Request_Log', 'motor_start_request'; ...
    'Motor_Stop_Request_Log', 'motor_stop_request'; ...
    'Motor_Emergency_Stop_Log', 'motor_emergency_stop'; ...
    'Motor_Driver_Fault_Log', 'motor_driver_fault'; ...
    'Motor_Hardware_Gate_Log', 'motor_hardware_gate'; ...
    'Motor_Measurement_Invalid_Log', 'motor_measurement_invalid'; ...
    'Motor_Reset_Allowed_Log', 'motor_reset_allowed'};
loggingPath = [modelName '/Motor_Stateflow_Test_Logging'];
add_block('simulink/Ports & Subsystems/Subsystem', loggingPath, ...
    'Position', [1510 640 1740 1000], ...
    'BackgroundColor', 'gray');
Simulink.SubSystem.deleteContents(loggingPath);
for logIndex = 1:size(loggingDefinitions, 1)
    y = 35 + 45 * logIndex;
    add_block('simulink/Sources/In1', ...
        [loggingPath '/' loggingDefinitions{logIndex, 1} '_In'], ...
        'Port', num2str(logIndex), ...
        'Position', [20 y 50 y + 14]);
    add_block('simulink/Sinks/To Workspace', ...
        [loggingPath '/' loggingDefinitions{logIndex, 1}], ...
        'VariableName', loggingDefinitions{logIndex, 2}, ...
        'SaveFormat', 'Timeseries', ...
        'Position', [190 y - 8 330 y + 22]);
    add_line(loggingPath, ...
        [loggingDefinitions{logIndex, 1} '_In/1'], ...
        [loggingDefinitions{logIndex, 1} '/1'], 'autorouting', 'on');
end
annotation = Simulink.Annotation(loggingPath, sprintf([ ...
    'HARNESS-ONLY TEST LOGGING\n' ...
    'Collects Stateflow, calibration, alignment and fault evidence.\n' ...
    'This subsystem is not present in the ERT controller target.']));
annotation.Position = [70 10 360 70];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'gray';
Simulink.BlockDiagram.arrangeSystem(loggingPath);
end

function removePreviousIntegration(modelName)
blockNames = {'Motor_State_Machine_100us', 'Motor_Safety_Monitor_100us', ...
    'Motor_Supervisor_1ms', 'Fast_Safety_Gate_100us', ...
    'Command_Arbiter_1ms', 'Fast_Protection_100us', ...
    'Fault_Latch_Manager_100us', 'Final_PWM_Arbiter_100us', ...
    'Average_Plant_Enable_Map', 'Slow_Safety_Monitor_1ms', ...
    'Current_Offset_Calibration_100us', 'Alignment_DQ_Override_100us', ...
    'Start_Threshold_Rpm', 'Start_Command_Sample_1ms', 'Start_Command', ...
    'Stateflow_Speed_Command_Gate', 'Safe_Duty_50pct', ...
    'FastFault_To_1ms', 'AnyFault_To_1ms', 'CalibrationDone_To_1ms', ...
    'EmergencyStop_To_1ms', 'DriverFault_To_1ms', ...
    'HardwareGate_To_1ms', ...
    'SupervisorPwmEnable_To_100us', 'CalibrationEnable_To_100us', ...
    'SupervisorPwmRequest_To_100us', 'ResetAllowed_To_100us', ...
    'Overspeed_To_100us', 'Undervoltage_To_100us', ...
    'Overvoltage_To_100us', ...
    'CalibrationReset_To_100us', 'AlignmentEnable_To_100us', ...
    'ControllerReset_To_100us', 'Supervisor_Fault_OR', ...
    'Stateflow_PWM_Gate_A', 'Stateflow_PWM_Gate_B', ...
    'Stateflow_PWM_Gate_C', 'Motor_Stateflow_Test_Logging', ...
    'Motor_Control_Enable_Log', ...
    'Motor_PWM_Enable_Log', 'Motor_State_Code_Log', ...
    'Motor_Calibration_Enable_Log', 'Motor_Calibration_Done_Log', ...
    'Motor_Alignment_Enable_Log', 'Motor_Current_Offset_A_Log', ...
    'Motor_Current_Offset_B_Log', 'Motor_Corrected_Current_A_Log', ...
    'Motor_Corrected_Current_B_Log', 'Motor_Applied_Vd_Log', ...
    'Motor_Applied_Vq_Log', 'Motor_Reset_Ack_Log', ...
    'Motor_Fault_Detected_Log', 'Motor_Fast_Fault_Log', ...
    'Motor_Alignment_Command_Held_Log', ...
    'Motor_Supervisor_PWM_Request_Log', 'Motor_PWM_Request_Held_Log', ...
    'Motor_Fault_Bits_Log', 'Motor_Fault_Code_Log', ...
    'Motor_Start_Request_Log', 'Motor_Stop_Request_Log', ...
    'Motor_Emergency_Stop_Log', 'Motor_Driver_Fault_Log', ...
    'Motor_Hardware_Gate_Log', 'Motor_Measurement_Invalid_Log', ...
    'Motor_Reset_Allowed_Log', ...
    'Motor_State_Code_Terminator', ...
    'FaultResetAck', 'StartRequest', 'StopRequest', 'EmergencyStop', ...
    'DriverFault', 'FaultResetRequest', 'HardwareGate', ...
    'MeasurementValid', 'Fault_Test_Command', 'Fault_Source_OR', ...
    'Fault_Reset_Ack', 'Start_Request_Command', 'Stop_Request_Command', ...
    'Emergency_Stop_Command', 'Driver_Fault_Command', ...
    'Fault_Reset_Request', 'Hardware_Gate_Command', ...
    'Measurement_Valid_Command', 'Test_Current_Offset_A', ...
    'Test_Current_Offset_B', 'Fast_Overcurrent_Test_A', ...
    'Measured_Current_A_With_Test_Offset', ...
    'Measured_Current_B_With_Test_Offset'};
for blockIndex = 1:numel(blockNames)
    blockPath = [modelName '/' blockNames{blockIndex}];
    if getSimulinkBlockHandle(blockPath) ~= -1
        delete_block(blockPath);
    end
end

marker = 'STATEFLOW MOTOR SUPERVISOR V2.1.0';
annotationHandles = find_system(modelName, 'FindAll', 'on', ...
    'MatchFilter', @Simulink.match.allVariants, 'Type', 'annotation');
for annotationIndex = 1:numel(annotationHandles)
    annotationObject = get_param(annotationHandles(annotationIndex), 'Object');
    if contains(annotationObject.Text, marker)
        delete(annotationObject);
    end
end
end

function disconnectInport(blockPath, portIndex)
if getSimulinkBlockHandle(blockPath) == -1
    return;
end
portHandles = get_param(blockPath, 'PortHandles');
if numel(portHandles.Inport) < portIndex
    return;
end
lineHandle = get_param(portHandles.Inport(portIndex), 'Line');
if lineHandle ~= -1
    delete_line(lineHandle);
end
end

function addStateflowAnnotation(modelName)
annotationText = sprintf(['STATEFLOW MOTOR SUPERVISOR V2.1.0\n' ...
    'States: 1 INIT | 2 READY | 3 CALIB | 4 ALIGN | 5 RUN | 6 FAULT\n' ...
    'Supervisor: 1 ms | current FOC, protection and PWM arbitration: 100 us\n' ...
    'Calibration, alignment and protection thresholds: PMSM_FOC_Data.sldd\n' ...
    'Stateflow owns SupervisorPwmRequest only; Final_PWM_Arbiter owns PwmEnable.\n' ...
    'FAULT clears only after explicit reset preconditions and all raw faults clear.']);
annotationObject = Simulink.Annotation(modelName, annotationText);
annotationObject.Position = [1040 680 1600 830];
annotationObject.FontSize = 10;
annotationObject.ForegroundColor = 'blue';
annotationObject.BackgroundColor = 'lightBlue';
end

function addTaskContractAnnotation(modelName)
annotationText = sprintf(['DUAL-RATE TASK CONTRACT (ARC-005)\n' ...
    '100 us / phase 0 / budget 70 us: validity, Clarke/Park, current PI, ' ...
    'decoupling, inverse transforms, SVPWM, fast protection, fault latch, PWM arbiter\n' ...
    '1 ms / phase 0 / budget 400 us: command arbiter, speed PI, Stateflow, ' ...
    'slow safety and status/diagnostics\n' ...
    'All cross-rate signals use named Rate Transition snapshots. ' ...
    'Latency: hardware gate same cycle; software OC <=100 us; start/stop/state <=1 ms.\n' ...
    'Budgets are design allocations; target WCET measurement remains M9 work.']);
annotationObject = Simulink.Annotation(modelName, annotationText);
annotationObject.Name = 'DUAL_RATE_TASK_CONTRACT';
annotationObject.Position = [1040 840 1760 1015];
annotationObject.FontSize = 9;
annotationObject.ForegroundColor = 'blue';
annotationObject.BackgroundColor = 'yellow';
end

function cleanupDanglingLines(parent)
% Deleting one branch can invalidate sibling handles returned by an earlier
% find_system call. Delete at most one branch per scan and then rescan.
while true
    lineHandles = find_system(parent, 'FindAll', 'on', ...
        'SearchDepth', 1, 'Type', 'line');
    removedLine = false;
    for lineIndex = 1:numel(lineHandles)
        try
            sourcePort = get_param(lineHandles(lineIndex), 'SrcPortHandle');
            destinationPorts = get_param(lineHandles(lineIndex), 'DstPortHandle');
            if isempty(sourcePort) || sourcePort == -1 || ...
                    isempty(destinationPorts) || any(destinationPorts == -1)
                delete_line(lineHandles(lineIndex));
                removedLine = true;
                break;
            end
        catch
            % The handle was invalidated by a sibling branch deletion.
            removedLine = true;
            break;
        end
    end
    if ~removedLine
        break;
    end
end
end
