function report = apply_pmsm_foc_bus_interface_v21(modelName)
%APPLY_PMSM_FOC_BUS_INTERFACE_V21 Wrap scalar internals in typed Bus ports.
% This changes only the standalone controller boundary. The existing FOC
% implementation and verification harness remain numerically unchanged.

if nargin < 1
    modelName = 'PMSM_FOC_DualPlant_Controller_v21';
end
assert(bdIsLoaded(modelName), 'Load %s before applying its Bus interface.', ...
    modelName);

scalarInputNames = {'SpeedReferenceRpm', 'SpeedRpm', 'PhaseCurrentA', ...
    'PhaseCurrentB', 'ElectricalAngleRad', 'DcBusVoltage', 'FaultResetAck'};
scalarOutputNames = {'DutyA', 'DutyB', 'DutyC', 'IqReference', ...
    'IdMeasured', 'IqMeasured', 'VdCommand', 'VqCommand'};

inputDestinations = struct;
for inputIndex = 1:numel(scalarInputNames)
    inputDestinations.(scalarInputNames{inputIndex}) = ...
        captureInputDestinations(modelName, scalarInputNames{inputIndex});
end
outputSources = struct;
for outputIndex = 1:numel(scalarOutputNames)
    outputSources.(scalarOutputNames{outputIndex}) = ...
        captureOutputSource(modelName, scalarOutputNames{outputIndex});
end

deleteRootPortBlocks(modelName, 'Inport');
deleteRootPortBlocks(modelName, 'Outport');
deleteIfPresent([modelName '/ControlCommand_Selector']);
deleteIfPresent([modelName '/Measurement_Selector']);
deleteIfPresent([modelName '/ControlStatus_Creator']);
deleteIfPresent([modelName '/FaultBits_U32']);
deleteIfPresent([modelName '/FaultCode_U16']);
deleteIfPresent([modelName '/StatusFault_To_100us']);
deleteIfPresent([modelName '/StatusState_To_100us']);
deleteIfPresent([modelName '/VoltageLimit_Inactive']);
deleteIfPresent([modelName '/MeasurementValid_Echo']);
deleteIfPresent([modelName '/BUS_INTERFACE_CONTRACT']);
deleteNamedPrefix(modelName, 'UnusedCommand_');
deleteNamedPrefix(modelName, 'UnusedMeasurement_');
cleanupDanglingLines(modelName);

add_block('simulink/Sources/In1', [modelName '/ControlCommand'], ...
    'Port', '1', 'OutDataTypeStr', 'Bus: ControlCommandBus', ...
    'BusOutputAsStruct', 'on', 'Position', [20 65 90 95]);
commandElements = {'StartRequest', 'StopRequest', 'EmergencyStop', ...
    'Direction', 'SpeedReferenceRpm', 'TorqueReferenceNm', ...
    'FaultResetRequest'};
add_block('simulink/Signal Routing/Bus Selector', ...
    [modelName '/ControlCommand_Selector'], ...
    'OutputSignals', strjoin(commandElements, ','), ...
    'Position', [135 35 255 205]);

add_block('simulink/Sources/In1', [modelName '/Measurement'], ...
    'Port', '2', 'OutDataTypeStr', 'Bus: MeasurementBus', ...
    'BusOutputAsStruct', 'on', 'Position', [20 285 90 315]);
measurementElements = {'PhaseCurrentA', 'PhaseCurrentB', 'PhaseCurrentC', ...
    'DcBusVoltage', 'ElectricalAngleRad', 'MechanicalSpeedRpm', 'Valid', ...
    'TimestampSeconds', 'FreshnessTicks'};
add_block('simulink/Signal Routing/Bus Selector', ...
    [modelName '/Measurement_Selector'], ...
    'OutputSignals', strjoin(measurementElements, ','), ...
    'Position', [135 235 265 475]);

add_line(modelName, 'ControlCommand/1', 'ControlCommand_Selector/1', ...
    'autorouting', 'on');
add_line(modelName, 'Measurement/1', 'Measurement_Selector/1', ...
    'autorouting', 'on');

commandPortHandles = get_param([modelName '/ControlCommand_Selector'], ...
    'PortHandles');
measurementPortHandles = get_param([modelName '/Measurement_Selector'], ...
    'PortHandles');
connectDestinations(modelName, commandPortHandles.Outport(5), ...
    inputDestinations.SpeedReferenceRpm);
connectDestinations(modelName, commandPortHandles.Outport(7), ...
    inputDestinations.FaultResetAck);
connectDestinations(modelName, measurementPortHandles.Outport(1), ...
    inputDestinations.PhaseCurrentA);
connectDestinations(modelName, measurementPortHandles.Outport(2), ...
    inputDestinations.PhaseCurrentB);
connectDestinations(modelName, measurementPortHandles.Outport(4), ...
    inputDestinations.DcBusVoltage);
connectDestinations(modelName, measurementPortHandles.Outport(5), ...
    inputDestinations.ElectricalAngleRad);
connectDestinations(modelName, measurementPortHandles.Outport(6), ...
    inputDestinations.SpeedRpm);

unusedCommandIndexes = [1 2 3 4 6];
for unusedIndex = 1:numel(unusedCommandIndexes)
    elementIndex = unusedCommandIndexes(unusedIndex);
    terminatorName = ['UnusedCommand_' commandElements{elementIndex}];
    add_block('simulink/Sinks/Terminator', ...
        [modelName '/' terminatorName], ...
        'Position', [315 25 + 35 * unusedIndex 335 45 + 35 * unusedIndex]);
    connectSource(modelName, commandPortHandles.Outport(elementIndex), ...
        get_param([modelName '/' terminatorName], 'PortHandles'), 'Inport');
end
unusedMeasurementIndexes = [3 8 9];
for unusedIndex = 1:numel(unusedMeasurementIndexes)
    elementIndex = unusedMeasurementIndexes(unusedIndex);
    terminatorName = ['UnusedMeasurement_' measurementElements{elementIndex}];
    add_block('simulink/Sinks/Terminator', ...
        [modelName '/' terminatorName], ...
        'Position', [315 300 + 40 * unusedIndex 335 320 + 40 * unusedIndex]);
    connectSource(modelName, measurementPortHandles.Outport(elementIndex), ...
        get_param([modelName '/' terminatorName], 'PortHandles'), 'Inport');
end

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [modelName '/FaultBits_U32'], 'OutDataTypeStr', 'uint32', ...
    'Position', [1450 650 1510 680]);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [modelName '/FaultCode_U16'], 'OutDataTypeStr', 'uint16', ...
    'Position', [1450 700 1510 730]);
add_block('simulink/Signal Attributes/Rate Transition', ...
    [modelName '/StatusFault_To_100us'], 'OutPortSampleTime', '0.0001', ...
    'Position', [1360 675 1430 705]);
add_block('simulink/Signal Attributes/Rate Transition', ...
    [modelName '/StatusState_To_100us'], 'OutPortSampleTime', '0.0001', ...
    'Position', [1360 620 1430 650]);
add_block('simulink/Sources/Constant', ...
    [modelName '/VoltageLimit_Inactive'], 'Value', 'false', ...
    'OutDataTypeStr', 'boolean', 'Position', [1450 760 1510 790]);
add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [modelName '/MeasurementValid_Echo'], 'OutDataTypeStr', 'boolean', ...
    'Position', [1450 805 1510 835]);
faultSource = outputPort(modelName, 'Supervisor_Fault_OR', 1);
connectDestinations(modelName, faultSource, ...
    inputPort(modelName, 'StatusFault_To_100us', 1));
fastStatusFaultSource = outputPort(modelName, 'StatusFault_To_100us', 1);
connectDestinations(modelName, fastStatusFaultSource, ...
    inputPort(modelName, 'FaultBits_U32', 1));
connectDestinations(modelName, fastStatusFaultSource, ...
    inputPort(modelName, 'FaultCode_U16', 1));
connectDestinations(modelName, ...
    outputPort(modelName, 'Motor_Supervisor_1ms', 3), ...
    inputPort(modelName, 'StatusState_To_100us', 1));
connectDestinations(modelName, measurementPortHandles.Outport(7), ...
    inputPort(modelName, 'MeasurementValid_Echo', 1));

statusElements = {'DutyA', 'DutyB', 'DutyC', 'IqReference', ...
    'IdMeasured', 'IqMeasured', 'VdCommand', 'VqCommand', 'PwmEnable', ...
    'MotorStateCode', 'FaultBits', 'FaultCode', 'CurrentLimitActive', ...
    'VoltageLimitActive', 'MeasurementValid'};
add_block('simulink/Signal Routing/Bus Creator', ...
    [modelName '/ControlStatus_Creator'], ...
    'Inputs', num2str(numel(statusElements)), ...
    'OutDataTypeStr', 'Bus: ControlStatusBus', ...
    'NonVirtualBus', 'off', 'Position', [1910 390 1915 760]);
add_block('simulink/Sinks/Out1', [modelName '/ControlStatus'], ...
    'Port', '1', 'OutDataTypeStr', 'Bus: ControlStatusBus', ...
    'Position', [1990 555 2060 585]);

statusSources = { ...
    outputSources.DutyA; outputSources.DutyB; outputSources.DutyC; ...
    outputSources.IqReference; outputSources.IdMeasured; ...
    outputSources.IqMeasured; outputSources.VdCommand; ...
    outputSources.VqCommand; ...
    outputPort(modelName, 'Fast_Safety_Gate_100us', 1); ...
    outputPort(modelName, 'StatusState_To_100us', 1); ...
    outputPort(modelName, 'FaultBits_U32', 1); ...
    outputPort(modelName, 'FaultCode_U16', 1); ...
    outputPort(modelName, 'Fast_Safety_Gate_100us', 2); ...
    outputPort(modelName, 'VoltageLimit_Inactive', 1); ...
    outputPort(modelName, 'MeasurementValid_Echo', 1)};
creatorPorts = get_param([modelName '/ControlStatus_Creator'], 'PortHandles');
for statusIndex = 1:numel(statusElements)
    lineHandle = add_line(modelName, statusSources{statusIndex}, ...
        creatorPorts.Inport(statusIndex), 'autorouting', 'on');
    set_param(lineHandle, 'Name', statusElements{statusIndex});
end
add_line(modelName, 'ControlStatus_Creator/1', 'ControlStatus/1', ...
    'autorouting', 'on');

annotation = Simulink.Annotation(modelName, sprintf([ ...
    'BUS INTERFACE CONTRACT (ARC-002)\n' ...
    'ControlCommandBus + MeasurementBus -> scalar internal components -> ControlStatusBus\n' ...
    'Unused explicit commands are contract placeholders for ARC-003; no control semantics changed']));
annotation.Name = 'BUS_INTERFACE_CONTRACT';
annotation.Position = [420 20 1160 95];
annotation.ForegroundColor = 'blue';
annotation.BackgroundColor = 'lightBlue';

cleanupDanglingLines(modelName);
set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, [], 'OverwriteIfChangedOnDisk', true);

report.InputCount = numel(find_system(modelName, 'SearchDepth', 1, ...
    'BlockType', 'Inport'));
report.OutputCount = numel(find_system(modelName, 'SearchDepth', 1, ...
    'BlockType', 'Outport'));
report.ControlCommandType = get_param([modelName '/ControlCommand'], ...
    'OutDataTypeStr');
report.MeasurementType = get_param([modelName '/Measurement'], ...
    'OutDataTypeStr');
report.ControlStatusType = get_param([modelName '/ControlStatus'], ...
    'OutDataTypeStr');
report.Pass = report.InputCount == 2 && report.OutputCount == 1 && ...
    strcmp(report.ControlCommandType, 'Bus: ControlCommandBus') && ...
    strcmp(report.MeasurementType, 'Bus: MeasurementBus') && ...
    strcmp(report.ControlStatusType, 'Bus: ControlStatusBus');
fprintf('CODEX_BUS_INTERFACE_SIGNATURE=%dBI-%dBO\n', ...
    report.InputCount, report.OutputCount);
fprintf('CODEX_BUS_INTERFACE_PASS=%d\n', report.Pass);
end

function destinations = captureInputDestinations(modelName, blockName)
path = [modelName '/' blockName];
assert(getSimulinkBlockHandle(path) ~= -1, ...
    'Expected scalar input %s is missing.', path);
ports = get_param(path, 'PortHandles');
lineHandle = get_param(ports.Outport(1), 'Line');
assert(lineHandle ~= -1, 'Scalar input %s is not connected.', path);
destinations = get_param(lineHandle, 'DstPortHandle');
destinations = destinations(destinations ~= -1);
assert(~isempty(destinations), 'Scalar input %s has no destinations.', path);
end

function source = captureOutputSource(modelName, blockName)
path = [modelName '/' blockName];
assert(getSimulinkBlockHandle(path) ~= -1, ...
    'Expected scalar output %s is missing.', path);
ports = get_param(path, 'PortHandles');
lineHandle = get_param(ports.Inport(1), 'Line');
assert(lineHandle ~= -1, 'Scalar output %s is not connected.', path);
source = get_param(lineHandle, 'SrcPortHandle');
assert(source ~= -1, 'Scalar output %s has no source.', path);
end

function deleteRootPortBlocks(modelName, blockType)
paths = find_system(modelName, 'SearchDepth', 1, 'BlockType', blockType);
for pathIndex = 1:numel(paths)
    delete_block(paths{pathIndex});
end
end

function deleteNamedPrefix(modelName, prefix)
blocks = find_system(modelName, 'SearchDepth', 1, 'Type', 'Block');
for blockIndex = 1:numel(blocks)
    [~, name] = fileparts(blocks{blockIndex});
    if startsWith(name, prefix)
        delete_block(blocks{blockIndex});
    end
end
end

function deleteIfPresent(path)
if getSimulinkBlockHandle(path) ~= -1
    delete_block(path);
end
end

function connectDestinations(modelName, sourcePort, destinations)
for destinationIndex = 1:numel(destinations)
    destination = destinations(destinationIndex);
    existingLine = get_param(destination, 'Line');
    if existingLine ~= -1
        delete_line(existingLine);
    end
    add_line(modelName, sourcePort, destination, 'autorouting', 'on');
end
end

function connectSource(modelName, sourcePort, destinationPorts, fieldName)
destination = destinationPorts.(fieldName)(1);
connectDestinations(modelName, sourcePort, destination);
end

function port = inputPort(modelName, blockName, index)
ports = get_param([modelName '/' blockName], 'PortHandles');
port = ports.Inport(index);
end

function port = outputPort(modelName, blockName, index)
ports = get_param([modelName '/' blockName], 'PortHandles');
port = ports.Outport(index);
end

function cleanupDanglingLines(parent)
lineHandles = find_system(parent, 'FindAll', 'on', 'SearchDepth', 1, ...
    'Type', 'line');
for lineIndex = 1:numel(lineHandles)
    try
        sourcePort = get_param(lineHandles(lineIndex), 'SrcPortHandle');
        destinationPorts = get_param(lineHandles(lineIndex), 'DstPortHandle');
        if isempty(sourcePort) || sourcePort == -1 || ...
                isempty(destinationPorts) || any(destinationPorts == -1)
            delete_line(lineHandles(lineIndex));
        end
    catch
    end
end
end
