function summary = verify_pmsm_foc_reproducibility_v21
%VERIFY_PMSM_FOC_REPRODUCIBILITY_V21 Repeat the complete clean build twice.
% Both runs start by restoring the v2.0.0 source models, applying the v2.1.0
% component/Stateflow refactor, running every MIL test, and generating ERT
% code. Semantic model checksums, interfaces, configurations, key metrics,
% and all PASS gates must agree before the reproducibility report can pass.

versionDirectory = fileparts(mfilename('fullpath'));
previousDirectory = pwd;
directoryCleanup = onCleanup(@() cd(previousDirectory));
cd(versionDirectory);

fprintf('CODEX_REPRODUCIBILITY_RUN=1/2\n');
firstRun = build_pmsm_foc_dualplant_v21( ...
    'CleanBuild', true, 'BatchMode', true, 'ExportImages', false);

fprintf('CODEX_REPRODUCIBILITY_RUN=2/2\n');
secondRun = build_pmsm_foc_dualplant_v21( ...
    'CleanBuild', true, 'BatchMode', true, 'ExportImages', false);

summary.FirstRun = firstRun;
summary.SecondRun = secondRun;
summary.ControllerChecksumMatch = strcmp( ...
    firstRun.ControllerChecksum, secondRun.ControllerChecksum);
summary.HarnessChecksumMatch = strcmp( ...
    firstRun.HarnessChecksum, secondRun.HarnessChecksum);
summary.InterfaceMatch = strcmp( ...
    firstRun.InterfaceSignature, secondRun.InterfaceSignature);
summary.ControllerConfigurationMatch = isequal( ...
    firstRun.ControllerConfiguration, secondRun.ControllerConfiguration);
summary.HarnessConfigurationMatch = isequal( ...
    firstRun.HarnessConfiguration, secondRun.HarnessConfiguration);
summary.NativeMetricMaximumDelta = maximumMetricDelta( ...
    firstRun.NativeMetrics, secondRun.NativeMetrics);
summary.McbMetricMaximumDelta = maximumMetricDelta( ...
    firstRun.McbMetrics, secondRun.McbMetrics);
summary.MetricTolerance = 1.0e-6;
summary.MetricsMatch = summary.NativeMetricMaximumDelta <= ...
    summary.MetricTolerance && summary.McbMetricMaximumDelta <= ...
    summary.MetricTolerance;
summary.BothRunsPass = firstRun.OverallPass && secondRun.OverallPass;
summary.Pass = summary.ControllerChecksumMatch && ...
    summary.HarnessChecksumMatch && summary.InterfaceMatch && ...
    summary.ControllerConfigurationMatch && ...
    summary.HarnessConfigurationMatch && summary.MetricsMatch && ...
    summary.BothRunsPass;

writeReproducibilityReport(versionDirectory, summary);
fprintf('CODEX_REPRO_CONTROLLER_CHECKSUM_MATCH=%d\n', ...
    summary.ControllerChecksumMatch);
fprintf('CODEX_REPRO_HARNESS_CHECKSUM_MATCH=%d\n', ...
    summary.HarnessChecksumMatch);
fprintf('CODEX_REPRO_INTERFACE_MATCH=%d\n', summary.InterfaceMatch);
fprintf('CODEX_REPRO_NATIVE_MAX_DELTA=%.9g\n', ...
    summary.NativeMetricMaximumDelta);
fprintf('CODEX_REPRO_MCB_MAX_DELTA=%.9g\n', ...
    summary.McbMetricMaximumDelta);
fprintf('CODEX_REPRO_PASS=%d\n', summary.Pass);
assert(summary.Pass, ...
    'The two clean builds did not produce the same verified baseline.');
end

function delta = maximumMetricDelta(firstMetrics, secondMetrics)
fieldNames = {'FinalSpeedRpm', 'MaximumSpeedRpm', 'MinimumSpeedRpm', ...
    'MaximumAbsIqA', 'MinimumDuty', 'MaximumDuty', 'FinalTorqueNm'};
deltas = zeros(size(fieldNames));
for fieldIndex = 1:numel(fieldNames)
    fieldName = fieldNames{fieldIndex};
    deltas(fieldIndex) = abs(firstMetrics.(fieldName) - ...
        secondMetrics.(fieldName));
end
delta = max(deltas);
end

function writeReproducibilityReport(versionDirectory, summary)
reportPath = fullfile(versionDirectory, ...
    'baseline_reproducibility_report.txt');
reportHandle = fopen(reportPath, 'w');
assert(reportHandle ~= -1, ...
    'Unable to create baseline reproducibility report.');
reportCleanup = onCleanup(@() fclose(reportHandle));

fprintf(reportHandle, 'PMSM FOC Dual Plant v2.1.0 baseline reproducibility\n');
fprintf(reportHandle, 'Required clean build count: 2\n');
writeRun(reportHandle, 'Run 1', summary.FirstRun);
writeRun(reportHandle, 'Run 2', summary.SecondRun);
fprintf(reportHandle, 'Controller checksum match: %d\n', ...
    summary.ControllerChecksumMatch);
fprintf(reportHandle, 'Harness checksum match: %d\n', ...
    summary.HarnessChecksumMatch);
fprintf(reportHandle, 'Generated interface match: %d\n', ...
    summary.InterfaceMatch);
fprintf(reportHandle, 'Controller configuration match: %d\n', ...
    summary.ControllerConfigurationMatch);
fprintf(reportHandle, 'Harness configuration match: %d\n', ...
    summary.HarnessConfigurationMatch);
fprintf(reportHandle, 'Metric comparison tolerance: %.9g\n', ...
    summary.MetricTolerance);
fprintf(reportHandle, 'Native maximum metric delta: %.9g\n', ...
    summary.NativeMetricMaximumDelta);
fprintf(reportHandle, 'MathWorks maximum metric delta: %.9g\n', ...
    summary.McbMetricMaximumDelta);
fprintf(reportHandle, 'Both complete verification runs pass: %d\n', ...
    summary.BothRunsPass);
fprintf(reportHandle, 'Baseline reproducibility pass: %d\n', summary.Pass);
end

function writeRun(reportHandle, label, runReport)
fprintf(reportHandle, '%s started at: %s\n', label, runReport.BuildStartedAt);
fprintf(reportHandle, '%s completed at: %s\n', label, runReport.BuildCompletedAt);
fprintf(reportHandle, '%s duration s: %.9g\n', ...
    label, runReport.BuildDurationSeconds);
fprintf(reportHandle, '%s clean build: %d\n', label, runReport.CleanBuild);
fprintf(reportHandle, '%s batch mode: %d\n', label, runReport.BatchMode);
fprintf(reportHandle, '%s Git commit: %s\n', ...
    label, runReport.Environment.GitCommit);
fprintf(reportHandle, '%s controller checksum: %s\n', ...
    label, runReport.ControllerChecksum);
fprintf(reportHandle, '%s harness checksum: %s\n', ...
    label, runReport.HarnessChecksum);
fprintf(reportHandle, '%s interface signature: %s\n', ...
    label, runReport.InterfaceSignature);
fprintf(reportHandle, '%s verification pass: %d\n', ...
    label, runReport.OverallPass);
end
